/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Input shape for `signRevocationList`. Field names map to spec
 * `RevocationEntry` (jti, revoked_at, reason).
 */
export interface RevocationEntryInput {
  /** JTI of the revoked TCT (UUID string). */
  jti: string
  /**
   * Unix seconds when the issuing peer revoked the TCT.
   * Defaults to the current time when omitted.
   */
  revokedAt?: number
  /** Optional human-readable reason. Not used in trust decisions. */
  reason?: string
}
/** Options for `buildManifest`. */
export interface ManifestOpts {
  /** Human-readable agent name; also the pinned-key identity subject. */
  displayName: string
  /** Absolute URL of this agent's handshake endpoint. */
  handshakeEndpoint: string
  /** Capabilities this agent offers to peers. */
  offeredCaps: Array<string>
  /** Capabilities a peer must grant back (optional). */
  requiredCaps?: Array<string>
  /** Manifest TTL in seconds (optional; defaults to 3600). */
  ttlSecs?: number
  /** Identity presentation type — `"pinned_key"` (default) or `"oidc"`. */
  identityType?: string
  /** OIDC issuer URL (required when `identityType="oidc"`). */
  oidcIssuer?: string
  /** OIDC subject identifier (required when `identityType="oidc"`). */
  oidcSubject?: string
  /**
   * Override the manifest's accepted_trust_anchors list. Defaults to
   * `[oidc_issuer]` for OIDC mode and `[]` for pinned-key mode.
   */
  acceptedTrustAnchors?: Array<string>
}
/**
 * Trust-anchor override for `newSession` / `newResponder`.
 *
 * JWKS provider is passed as a separate argument (napi-rs can't put a
 * class reference inside an `#[napi(object)]` struct).
 */
export interface SessionOpts {
  /**
   * Override the agent manifest's accepted_trust_anchors. `null`
   * reuses the manifest's list.
   */
  trustAnchors?: Array<string>
}
/**
 * Options for `AitpAgent.generate` and `AitpAgent.fromSeed`.
 *
 * Mirrors the Python SDK's `suite="ed25519"|"p256"` keyword argument so
 * the two SDKs share one shape per operation. `null`/omitted defaults
 * to `"ed25519"`.
 */
export interface GenerateOpts {
  /**
   * Signing suite. Accepted values: `"ed25519"` (default) or
   * `"p256"` (RFC-AITP-0001 §5.4.3).
   */
  suite?: string
}
/**
 * Outcome shape returned by `verifySessionBundle`. `kind` is `"clear"`
 * or `"degraded"`; `droppedAids` is empty in the `"clear"` case.
 */
export interface JsBundleOutcome {
  kind: string
  activeAids: Array<string>
  droppedAids: Array<string>
}
/**
 * Verify a `SessionBundleEnvelope` JSON. `nowUnixSecs` defaults to
 * the system clock. `revocationCheck` receives a JTI string and
 * returns true if revoked.
 */
export declare function verifySessionBundle(bundleEnvelopeJson: string, verifierAid: string, nowUnixSecs?: number | undefined | null, revocationCheck?: (...args: any[]) => any | undefined | null): JsBundleOutcome
/**
 * The verified delegation token's salient fields. Returned from
 * `verifyDelegation` and consumed by `AitpAgent.issueTctForDelegatee`.
 */
export interface JsDelegationVerified {
  /**
   * AID of the ultimate grantor (the original TCT issuer that gave grants
   * to `issuedBy`). The responder side checks this matches its own AID
   * before redeeming.
   */
  delegator: string
  /** AID of the recipient (C) — who will receive a fresh TCT. */
  delegatee: string
  /** AID of the agent that issued this delegation (B in the RFC). */
  issuedBy: string
  /** Capabilities being delegated. Always a subset of the source TCT's grants. */
  grants: Array<string>
  /** Unix-seconds expiry of the delegation token itself. */
  expiresAt: number
  /**
   * Delegatee's raw Ed25519 / P-256 public key, base64url-encoded. This is
   * the `cnf` binding — proves which key the issuer should bind to the
   * fresh TCT it mints.
   */
  cnf: string
}
/**
 * Verify a `DelegationEnvelope` JSON under **strict AITP v0.1**
 * (RFC-AITP-0006 single-hop). `verifierAid` is the verifier's own AID
 * string — verification fails if it doesn't match the token's `delegator`
 * field.
 *
 * Any token carrying a non-empty `chain` (a draft RFC-AITP-0011 multi-hop
 * delegation) is **rejected** with `DELEGATION_MULTIHOP_NOT_SUPPORTED`,
 * matching the Rust core default. To opt into multi-hop, build the SDK with
 * the `experimental-multihop-delegation` feature and call
 * `verifyDelegationExperimentalMultihop`.
 */
export declare function verifyDelegation(envelopeJson: string, verifierAid: string): JsDelegationVerified
/**
 * Verify a `DelegationEnvelope` JSON allowing **draft RFC-AITP-0011
 * multi-hop** chains up to `maxHops` total hops (`chain.length + 1`).
 *
 * This opts into behavior that is **not** part of AITP v0.1. It is only
 * compiled in under the `experimental-multihop-delegation` feature; a
 * default build exposes only the strict `verifyDelegation`.
 *
 * `maxHops` defaults to `DEFAULT_MAX_HOPS` (3, the RFC-AITP-0011 §2
 * recommended ceiling). Pass a smaller value for a tighter bound;
 * `maxHops = 0` reverts to strict v0.1 (rejects any non-empty chain).
 */
export declare function verifyDelegationExperimentalMultihop(envelopeJson: string, verifierAid: string, maxHops?: number | undefined | null): JsDelegationVerified
/**
 * Compute the RFC 7638 JWK thumbprint of the public key embedded in
 * an AID — the value an OIDC IdP MUST place in the JWT's `cnf.jkt`
 * claim when proving the key binding (RFC-AITP-0002 §2.2.1).
 *
 * Works for both Ed25519 (`aid:pubkey:ed25519:...`) and P-256
 * (`aid:pubkey:p256:...`) AIDs. Use this from your OIDC minter
 * closure so the bound peer correctly verifies the cnf binding —
 * implementing curve arithmetic by hand to derive the thumbprint
 * in JavaScript is both error-prone and a divergence risk.
 */
export declare function computeAidJkt(aid: string): string
/**
 * Compute the SHA-256 SPKI hash for an X.509 DER certificate. Returns
 * a 32-byte Buffer. Throws if `certDer` is not a parseable certificate.
 */
export declare function computeSpkiHash(certDer: Buffer): Buffer
/** Result of `processHello`: response body plus session id. */
export interface JsHelloAckResult {
  /** `MUTUAL_HELLO_ACK` envelope JSON — set as the HTTP response body. */
  ackJson: string
  /** Correlation id — set as the `X-Aitp-Session-Id` response header. */
  sessionId: string
}
/** Result of `processCommit`: response body plus the held TCT. */
export interface JsCommitAckResult {
  /** `MUTUAL_COMMIT_ACK` envelope JSON — set as the HTTP response body. */
  ackJson: string
  /** `TctEnvelope` JSON the initiator issued to us. */
  tctJson: string
}
/** The verified peer identity carried by a TCT. */
export interface JsTctIdentity {
  /** AID of the agent that issued (and is bound by) the TCT. */
  peerAid: string
  /** Capability grants the TCT authorizes. */
  grants: Array<string>
  /** Expiry, Unix seconds. */
  expiresAt: number
  /** TCT unique identifier (`jti`). */
  jti: string
}
/**
 * Verify a `ManifestEnvelope` JSON string. Throws on signature,
 * proof-of-possession, expiry, or identity-hint shape failures.
 * Used by the AITP Control Plane during agent enrollment.
 */
export declare function verifyManifestJson(manifestEnvelopeJson: string): void
/** An AITP agent: a signing key and (once built) its Manifest. */
export declare class AitpAgent {
  /**
   * Generate an agent with a fresh random signing key.
   *
   * `opts.suite` selects the algorithm — `"ed25519"` (default) or
   * `"p256"`. Symmetric with the Python SDK's
   * `AitpAgent.generate(suite="ed25519")`.
   *
   * ```ts
   * const ed = AitpAgent.generate();                       // Ed25519
   * const p  = AitpAgent.generate({ suite: 'p256' });      // P-256
   * ```
   */
  static generate(opts?: GenerateOpts | undefined | null): AitpAgent
  /**
   * Construct an agent from a 32-byte seed (deterministic).
   *
   * `opts.suite` matches `AitpAgent.generate`. For `"p256"`, a tiny
   * fraction of 32-byte seeds are not valid private scalars (zero
   * or ≥ curve order) and raise.
   *
   * Note: the prior `AitpAgent.fromP256Seed` factory and the
   * no-arg `AitpAgent.generate*` variants were removed in favor of
   * this parameterized API so the Node SDK matches the Python SDK
   * surface (CLAUDE.md mandates SDK symmetry).
   */
  static fromSeed(seed: Buffer, opts?: GenerateOpts | undefined | null): AitpAgent
  /** The agent's AID string (`aid:pubkey:...`). */
  get aid(): string
  /**
   * Build and sign the agent's Manifest. Returns `ManifestEnvelope`
   * JSON and caches the Manifest for `newSession` / `newResponder`.
   *
   * See `ManifestOpts.identityType` for the OIDC switch.
   */
  buildManifest(opts: ManifestOpts): string
  /**
   * Create a new outbound (initiator) handshake session.
   *
   * `jwks` is an optional `JwksProvider` used when the peer's
   * manifest advertises an OIDC identity. `opts.trustAnchors`
   * overrides the manifest's `accepted_trust_anchors`.
   */
  newSession(jwks?: JwksProvider | undefined | null, opts?: SessionOpts | undefined | null): JsInitiatorSession
  /**
   * Create a new inbound (responder) handshake session. Mirror of
   * `newSession`.
   */
  newResponder(jwks?: JwksProvider | undefined | null, opts?: SessionOpts | undefined | null): JsResponderSession
  /**
   * Verify a TCT JSON string and require `requiredGrant`. Rejects on
   * an invalid, mis-audienced, expired, or under-scoped TCT.
   *
   * `expectedAudience` defaults to `null`, which means "verify as the
   * holder" (RFC-AITP-0005 §9 receipt model — `this.aid` is used).
   * Resource servers verifying a TCT presented by a peer should pass
   * the TCT's own `audience` field as `expectedAudience` (in v0.1 this
   * equals `subject`).
   */
  verifyTct(tctJson: string, requiredGrant: string, expectedAudience?: string | undefined | null): JsTctIdentity
  /**
   * Like `verifyTct`, but consults a `TctStore` first: a byte-identical,
   * already-verified, still-valid TCT skips the signature check (the
   * verification hot path for an agent that sees the same TCT on many
   * requests). All cheap policy checks (expiry, audience, required grant)
   * still run on every call; only the signature check is elided.
   */
  verifyTctCached(tctJson: string, requiredGrant: string, store: JsTctStore, expectedAudience?: string | undefined | null): JsTctIdentity
  /** Build a `DelegationEnvelope` JSON from a held TCT (RFC-AITP-0006). */
  buildDelegation(heldTctEnvelopeJson: string, delegateeAid: string, delegateePubkeyB64U: string, scope: Array<string>, ttlSecs?: number | undefined | null): string
  /**
   * Mint a fresh `TctEnvelope` JSON for a delegatee after the verifier has
   * confirmed the delegation. The subject_pubkey binding is taken from the
   * verified token's `cnf` field.
   */
  issueTctForDelegatee(verified: JsDelegationVerified, ttlSecs?: number | undefined | null): string
  /**
   * Sign a `RevocationList` with this agent's key. `entries` carries
   * the revoked-TCT records; `expiresInSecs` defaults to 3600 s.
   * Returns the on-wire `RevocationListEnvelope` JSON.
   */
  signRevocationList(entries: Array<RevocationEntryInput>, expiresInSecs?: number | undefined | null): string
  /**
   * Holder side: build a `TctRenewalPayload` JSON for an in-band
   * renewal of `currentTctEnvelopeJson` (RFC-AITP-0005 §10).
   *
   * **Gated by the `experimental-renewal` Cargo feature.** Off in
   * the default `.node` artifact; build with
   * `napi build --release -- --features experimental-renewal`.
   */
  buildRenewalRequest(currentTctEnvelopeJson: string): string
  /**
   * Issuer side: verify a `TctRenewalPayload` JSON request and mint a
   * fresh `TctEnvelope` JSON.
   *
   * **Gated by the `experimental-renewal` Cargo feature.**
   */
  processRenewalRequest(requestPayloadJson: string, manifestExpUnixSecs: number, newTtlSecs: number): string
}
export type SessionBundleBuilderJs = SessionBundleBuilder
/**
 * Fluent builder for issuing a `SessionBundleEnvelope`. Constructed
 * from the coordinator's `AitpAgent`.
 *
 * The Rust struct is suffixed `Js` to avoid a name collision with the
 * `aitp_session_bundle::SessionBundleBuilder` imported above; the
 * `#[napi(js_name)]` attribute exposes it to JavaScript under the
 * plain name `SessionBundleBuilder` for parity with the Python SDK.
 */
export declare class SessionBundleBuilder {
  /** Construct a builder backed by `coordinator`'s signing key. */
  constructor(coordinator: AitpAgent)
  /** Set the session ID (UUIDv4 string). Defaults to a fresh one. */
  sessionId(uuidStr: string): this
  /** Override `issued_at` (unix seconds). Defaults to "now" at build. */
  issuedAt(unixSecs: number): this
  /** Add a participant entry. `tctEnvelopeJson` is a TctEnvelope JSON. */
  participant(aid: string, tctEnvelopeJson: string): this
  /** Construct, sign, and return the `SessionBundleEnvelope` JSON. */
  build(): string
}
/**
 * In-memory OIDC JWKS provider — issuer URL → list of JWK objects.
 *
 * The Node caller fetches the JWKS (the SDK has no HTTP client) and
 * hands the parsed objects to this provider. Implements `JwksResolver`
 * internally so the handshake state machine can dispatch through it.
 */
export declare class JwksProvider {
  /**
   * Construct from an object mapping issuer URLs to arrays of JWK
   * objects. Each JWK must be a standard RFC 7517 representation
   * (`kty`, `crv`, `x`, ...). Pass `{}` for an empty provider and
   * `upsert` later.
   */
  constructor(keys?: unknown | undefined | null)
  /**
   * Add or replace the JWKs for an issuer. `keys` is a JS array of
   * JWK objects.
   */
  upsert(issuer: string, keys: unknown): void
  /** Drop all keys for an issuer. */
  remove(issuer: string): void
  /** Return the issuer URLs currently registered. */
  issuers(): Array<string>
}
/**
 * Holds a list of 32-byte SPKI pins. `isPinned(certDer)` returns true
 * iff the cert's SPKI hash is in the list.
 */
export declare class SpkiPinVerifier {
  /**
   * Construct from an array of 32-byte Buffers. Throws if any pin is
   * not exactly 32 bytes.
   */
  constructor(pins: Array<Buffer>)
  /** Returns true iff the SPKI hash of `certDer` is in the pin list. */
  isPinned(certDer: Buffer): boolean
  /** Number of pins currently held. */
  get len(): number
}
/** Outbound handshake session — drives the initiator side. */
export declare class JsInitiatorSession {
  /**
   * Step 1 — build the `MUTUAL_HELLO` envelope.
   *
   * `oidcMintJwt`: required for OIDC agents. Receives the handshake-
   * generated `pop_nonce` (string) and must return the JWT (string).
   */
  buildHello(peerManifestJson: string, requestedGrants: Array<string>, oidcMintJwt?: (...args: any[]) => any | undefined | null): string
  /** Step 2 — process `MUTUAL_HELLO_ACK`, produce `MUTUAL_COMMIT`. */
  processHelloAck(helloAckJson: string, sessionId: string): string
  /**
   * Step 3 — process `MUTUAL_COMMIT_ACK`. Returns the `TctEnvelope`
   * JSON the peer issued to us.
   */
  complete(commitAckJson: string): string
}
/** Inbound handshake session — drives the responder side. */
export declare class JsResponderSession {
  /**
   * Process an incoming `MUTUAL_HELLO` envelope.
   *
   * `oidcMintJwt`: required for OIDC agents (see `JsInitiatorSession.buildHello`).
   */
  processHello(helloJson: string, oidcMintJwt?: (...args: any[]) => any | undefined | null): JsHelloAckResult
  /** Process an incoming `MUTUAL_COMMIT` envelope. */
  processCommit(commitJson: string): JsCommitAckResult
}
export type JsTctStore = TctStore
/**
 * A bounded, in-memory cache of **successful** TCT verifications, keyed by
 * the SHA-256 of the exact TCT envelope JSON bytes.
 *
 * Purpose: a high-throughput verifier (e.g. a writer agent checking a
 * capability on every request) that repeatedly sees the *same* TCT can skip
 * the Ed25519/P-256 signature verification after the first time.
 *
 * **Safety.** The key is a cryptographic hash of the exact signed bytes, so
 * only a byte-identical envelope — whose signature was already verified once
 * — can hit. A tampered token hashes differently, misses, and is fully
 * verified. The cheap policy checks (expiry, audience, required grant) are
 * re-run on **every** hit; only the signature check is elided. Eviction is
 * FIFO once `maxEntries` is reached.
 */
export declare class TctStore {
  /**
   * Create a cache holding at most `maxEntries` verified TCTs (FIFO
   * eviction). `maxEntries` must be >= 1.
   */
  constructor(maxEntries: number)
  /** Number of cached verifications currently held. */
  len(): number
  /** Drop all cached entries. */
  clear(): void
}
