"""Full four-message handshake with OIDC identity proofs (RFC-AITP-0002).

Uses an in-process mock OIDC issuer (Ed25519 key + by-hand JWT minting)
and the SDK's `JwksProvider` + `oidc_mint_jwt` callback to drive both
sides of the handshake without any HTTP I/O.
"""

# Defer annotation evaluation so PEP 604 unions (`bytes | None`) parse on
# Python 3.9, which the package still supports (requires-python >=3.9).
from __future__ import annotations

import base64
import hashlib
import json

import pytest
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

import aitp


def _b64url(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).decode("ascii").rstrip("=")


def _jwk_thumbprint_ed25519(pubkey_bytes: bytes) -> str:
    """RFC 7638 JWK thumbprint for an Ed25519 (OKP) key. Mirrors
    `aitp_crypto::thumbprint::compute_jwk_thumbprint`."""
    canonical = json.dumps(
        {"crv": "Ed25519", "kty": "OKP", "x": _b64url(pubkey_bytes)},
        separators=(",", ":"),
        sort_keys=True,
    )
    return _b64url(hashlib.sha256(canonical.encode()).digest())


class MockOidcIssuer:
    def __init__(self, issuer_url: str, kid: str = "kid-1", seed: bytes | None = None):
        self.issuer = issuer_url
        self.kid = kid
        self.priv = Ed25519PrivateKey.from_private_bytes(
            seed or bytes(range(32))
        )
        pub = self.priv.public_key()
        from cryptography.hazmat.primitives import serialization

        self.pub_bytes = pub.public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw,
        )

    def jwk(self) -> dict:
        return {
            "kty": "OKP",
            "crv": "Ed25519",
            "x": _b64url(self.pub_bytes),
            "kid": self.kid,
            "alg": "EdDSA",
            "use": "sig",
        }

    def mint(self, *, sub: str, aud: str, nonce: str, cnf_jkt: str, now: int) -> str:
        header = {"alg": "EdDSA", "typ": "JWT", "kid": self.kid}
        claims = {
            "iss": self.issuer,
            "sub": sub,
            "aud": aud,
            "iat": now,
            "exp": now + 3600,
            "nonce": nonce,
            "cnf": {"jkt": cnf_jkt},
        }
        h_b64 = _b64url(json.dumps(header, separators=(",", ":")).encode())
        p_b64 = _b64url(json.dumps(claims, separators=(",", ":")).encode())
        signing_input = f"{h_b64}.{p_b64}".encode()
        sig = self.priv.sign(signing_input)
        return f"{h_b64}.{p_b64}.{_b64url(sig)}"


ISSUER_URL = "https://idp.example.test/"  # canonical form (url::Url adds trailing slash)


def _agents():
    issuer = MockOidcIssuer(ISSUER_URL)
    provider = aitp.JwksProvider({ISSUER_URL: [issuer.jwk()]})

    alice = aitp.AitpAgent.generate()
    bob = aitp.AitpAgent.generate()
    a_manifest = alice.build_manifest(
        display_name="alice",
        handshake_endpoint="https://alice.example.test/aitp/handshake/",
        offered_caps=["demo.echo"],
        identity_type="oidc",
        oidc_issuer=ISSUER_URL,
        oidc_subject="alice",
    )
    b_manifest = bob.build_manifest(
        display_name="bob",
        handshake_endpoint="https://bob.example.test/aitp/handshake/",
        offered_caps=["demo.write"],
        identity_type="oidc",
        oidc_issuer=ISSUER_URL,
        oidc_subject="bob",
    )
    return issuer, provider, alice, bob, a_manifest, b_manifest


def _aid_jkt(aid: str) -> str:
    """Compute the JWK thumbprint for the Ed25519 pubkey embedded in an AID."""
    # AIDs from `agent.generate()` are Ed25519, encoded
    # as `aid:pubkey:<43chars>` (legacy) — strip the prefix and decode.
    if aid.startswith("aid:pubkey:ed25519:"):
        pk_b64 = aid[len("aid:pubkey:ed25519:") :]
    else:
        # Legacy untagged form: aid:pubkey:<43>
        pk_b64 = aid[len("aid:pubkey:") :]
    pk = base64.urlsafe_b64decode(pk_b64 + "==")[:32]
    return _jwk_thumbprint_ed25519(pk)


def test_full_oidc_handshake():
    issuer, provider, alice, bob, _a_manifest, b_manifest = _agents()

    a_jkt = _aid_jkt(alice.aid)
    b_jkt = _aid_jkt(bob.aid)
    import time

    now = int(time.time())

    # Alice's minter: receives the pop_nonce generated by the SDK and
    # mints a JWT bound to it. `aud` is Bob's AID (alice presents to bob).
    a_mint = lambda nonce: issuer.mint(
        sub="alice", aud=bob.aid, nonce=nonce, cnf_jkt=a_jkt, now=now
    )
    b_mint = lambda nonce: issuer.mint(
        sub="bob", aud=alice.aid, nonce=nonce, cnf_jkt=b_jkt, now=now
    )

    sess = alice.new_session(jwks=provider)
    rsess = bob.new_responder(jwks=provider)

    hello = sess.build_hello(b_manifest, ["demo.write"], oidc_mint_jwt=a_mint)
    hello_ack, sid = rsess.process_hello(hello, oidc_mint_jwt=b_mint)
    commit = sess.process_hello_ack(hello_ack, sid)
    commit_ack, bob_completed = rsess.process_commit(commit)
    alice_completed = sess.complete(commit_ack)

    # v0.2: completion is {"tct": <compact JWS>, "grant_voucher": ...}.
    alice_held = json.loads(alice_completed)["tct"]
    bob_held = json.loads(bob_completed)["tct"]

    a_ident = alice.verify_tct(alice_held, "demo.write")
    assert a_ident.peer_aid == bob.aid
    b_ident = bob.verify_tct(bob_held, "demo.echo")
    assert b_ident.peer_aid == alice.aid


def test_oidc_session_requires_mint_callback():
    _issuer, provider, alice, bob, _a_manifest, b_manifest = _agents()
    sess = alice.new_session(jwks=provider)
    with pytest.raises(ValueError, match="oidc_mint_jwt"):
        sess.build_hello(b_manifest, ["demo.write"])  # no callback


def test_oidc_responder_rejects_untrusted_issuer():
    """Responder configured to trust only ISSUER_URL must reject a HELLO
    whose JWT was minted by some other issuer."""
    issuer, provider, alice, bob, _a_manifest, b_manifest = _agents()
    other = MockOidcIssuer("https://attacker.example.test", kid="kid-2")
    # Trust only the legitimate issuer — `other` is unknown.
    a_jkt = _aid_jkt(alice.aid)
    import time

    now = int(time.time())
    a_mint = lambda nonce: other.mint(
        sub="alice", aud=bob.aid, nonce=nonce, cnf_jkt=a_jkt, now=now
    )

    sess = alice.new_session(jwks=provider)
    rsess = bob.new_responder(jwks=provider)

    # Alice's manifest says identity is OIDC issued by ISSUER_URL, but
    # the minted JWT comes from `other` — Bob's bootstrap_verify_peer
    # check on identity_hint.issuer ≠ JWT issuer should fire.
    # Build_hello may fail on its own (no JWKS for `other`) but we want
    # to confirm at minimum that the handshake doesn't complete.
    try:
        hello = sess.build_hello(b_manifest, ["demo.write"], oidc_mint_jwt=a_mint)
    except RuntimeError:
        return  # rejected at hello build (e.g. identity descriptor mismatch)
    # If hello built, the responder must reject it.
    with pytest.raises(RuntimeError):
        rsess.process_hello(hello, oidc_mint_jwt=lambda _n: "")
